---
name: Release

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/coregio
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Build a package
        run: |
            pip install pdm
            pdm build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
