---
name: validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Setup Python
        run: |
          pip install tox tox-pdm pdm
          pdm venv create ${{ matrix.version }}
          source .venv/bin/activate

      - name: Tox
        run: tox
